apiVersion: v1
data:
  config: |
    artifactRepository:
      archiveLogs: true
      s3:
        bucket: my-bucket
        endpoint: minio:9000
        insecure: true
        accessKeySecret:
          name: my-minio-cred
          key: accesskey
        secretKeySecret:
          name: my-minio-cred
          key: secretkey
    persistence:
      connectionPool:
        maxIdleConns: 100
        maxOpenConns: 0
      nodeStatusOffLoad: true
      archive: true
      mysql:
        host: mysql
        port: 3306
        database: work
        tableName: work_workflows
        userNameSecret:
          name: work-mysql-config
          key: username
        passwordSecret:
          name: work-mysql-config
          key: password
kind: ConfigMap
metadata:
  name: workflow-controller-configmap