apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: work-server-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: work-server-cluster-role
subjects:
  - kind: ServiceAccount
    name: work-server
    namespace: work
