apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

resources:
  - work-postgres-config-secret.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml

patchesStrategicMerge:
  - overlays/workflow-controller-configmap.yaml