# run forever
apiVersion: kubework.io/v1alpha1
kind: Workflow
metadata:
  name: forever
  labels:
    work-e2e: true
spec:
  entrypoint: main
  templates:
    - name: main
      container:
        image: docker/whalesay:latest
        command: [sh, "-c", "for I in $(seq 1 1000) ; do echo $I ; sleep 1s; done"]
