apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: work-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: work-role
subjects:
  - kind: ServiceAccount
    name: work
