apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: work-server-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: work-server-role
subjects:
- kind: ServiceAccount
  name: work-server
